### ISSUE TITLE
Recursively copy a directory without specifying every file in it

### ISSUE THREAD

**Issue by Googulator** [kohlschutter/copy-rename-maven-plugin#1]
Right now, rename supports directories, but copy for some reason doesn't. This means, the only way to copy a directory is by listing every file inside individually in the POM, which is prone to breakage when new files are added.

(Copied from https://github.com/coderplus/copy-rename-maven-plugin/issues/23)

**Comment by kohlschuetter** [comment]
Thanks for filing this request!

My priority for this fork is to keep it maintained, not necessarily extend it beyond its current functionality.

For copying directory trees, you're probably better off with using `maven-resources-plugin`, for example:

```
<plugin>
    <artifactId>maven-resources-plugin</artifactId>
    <executions>
        <execution>
            <id>copy-myfiles</id> <!-- change as required -->
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <phase>compile</phase> <!-- change as required -->
            <configuration>
                <outputDirectory>
                    ${project.build.directory}/classes-someotherDir</outputDirectory>  <!-- change as required -->
                <resources>
                    <resource>
                        <directory>
                            ${project.build.directory}/classes</directory> <!-- change as required -->
                        <includes>
                            <include>**</include>  <!-- change as required -->
                        </includes>
                    </resource>
                </resources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

If this doesn't work for you for some reason, please re-open this issue with some examples.
